import './globals.css';
import 'dayjs/locale/ko';
import dayjs from 'dayjs';
import { type Metadata } from 'next';
import localFont from 'next/font/local';
import { CoreProvider, MODAL_COMPONENTS } from '@/app';
import { Modal } from '@/features/modal';
import { cn } from '@/shared/lib/utils';
import { ThemeProvider } from '@/shared/ui/theme-provider';
import { Footer } from '@/widgets/footer';

dayjs.locale('ko');

const pretendard = localFont({
  src: '../src/fonts/PretendardVariable.woff2',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sans antialiased', pretendard.variable)}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <CoreProvider>
            <main className="flex-1">{children}</main>
            <Footer />
            <Modal components={MODAL_COMPONENTS} />
          </CoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
